resources:
  repositories:
  - repository: abs-tudelft
    type: github
    endpoint: github
    name: abs-tudelft/azure-pipelines-templates

variables:
  arrowVersion: 0.14.0

jobs:

- job:
  strategy:
    matrix:
      c:
        source: common/c
      common:
        source: common/cpp
      cerata:
        source: codegen/cerata
      fletchgen:
        source: codegen/fletchgen
      runtime:
        source: runtime/cpp
      echo:
        source: platforms/echo/runtime
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: steps/set-cc-cxx.yml@abs-tudelft
    parameters:
      cc: gcc-7
      cxx: g++-7
  - template: steps/install-arrow.yml@abs-tudelft
    parameters:
      version: $(arrowVersion)
  - template: steps/install-cmake.yml@abs-tudelft
  - template: steps/cmake.yml@abs-tudelft
    parameters:
      source: $(source)
      args: -DBUILD_TESTS=ON

- template: jobs/vhdeps.yml@abs-tudelft
  parameters:
    name: hardware
    args: ["--pattern '*_tc'", "--pattern ':!*/vhlib/*'"]
    sources: ['hardware']
    preSteps:
    - checkout: self
      submodules: true

- job: pyfletcher
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: steps/install-python.yml@abs-tudelft
    parameters:
      packages: ['pyarrow', 'numpy', 'cython']
  - template: steps/install-arrow.yml@abs-tudelft
    parameters:
      version: $(arrowVersion)
  - template: steps/install-cmake.yml@abs-tudelft
  - script: |
      python3 setup.py build
    displayName: Build
    workingDirectory: $(Build.SourcesDirectory)/runtime/python
  - script: |
      python3 setup.py bdist_wheel
    displayName: Wheel
    workingDirectory: $(Build.SourcesDirectory)/runtime/python
  - script: |
      pip3 install build/dist/pyfletcher*whl
    workingDirectory: $(Build.SourcesDirectory)/runtime/python
    displayName: Install wheel
  - script: |
      python3 -c "import pyfletcher"
    displayName: Test import

- job: manylinux
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      docker build --build-arg ARROW_VERSION=$(arrowVersion) --build-arg MANYLINUX=2010 -t pyfletcher-manylinux:2010 - < misc/Dockerfile.python &&
      docker run --rm -v $(Build.SourcesDirectory):/io pyfletcher-manylinux:2010
    displayName: Build pyfletcher manylinux wheels
  - template: steps/install-python.yml@abs-tudelft
  - script: |
      pip3 install build/dist/pyfletcher*37*manylinux*
    workingDirectory: $(Build.SourcesDirectory)/runtime/python
    displayName: Test manylinux wheel
  - script: |
      python3 -c "import pyfletcher"
    displayName: Test pyfletcher import

- template: jobs/mdbook-gh-pages.yml@abs-tudelft
  parameters:
    ref: refs/heads/develop
    preSteps:
    - template: ../steps/install-doxygen.yml
    - script: |
        doxygen
      workingDirectory: $(Build.SourcesDirectory)/codegen/fletchgen
      displayName: Doxygen (fletchgen)
    - script: |
        doxygen
      workingDirectory: $(Build.SourcesDirectory)/codegen/cerata
      displayName: Doxygen (cerata)
    - script: |
        doxygen
      workingDirectory: $(Build.SourcesDirectory)/runtime/cpp
      displayName: Doxygen (C++ runtime)
    beforePublishSteps:
    - script: |
        mkdir -p docs/book/api/cerata && mv codegen/cerata/docs/html docs/book/api/cerata &&
        mkdir -p docs/book/api/fletchgen && mv codegen/fletchgen/docs/html docs/book/api/fletchgen &&
        mkdir -p docs/book/api/fletcher-cpp && mv runtime/cpp/docs/html docs/book/api/fletcher-cpp
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Add API docs


